In [1]:
import pandas as pd
from pathlib import Path

PROCESSED_DIR = Path("../data/processed")

application_clean = pd.read_csv(
    PROCESSED_DIR / "application_clean.csv"
)

bureau_summary = pd.read_csv(
    PROCESSED_DIR / "bureau_summary.csv"
)

previous_summary = pd.read_csv(
    PROCESSED_DIR / "previous_application_summary.csv"
)

In [2]:
print(application_clean.shape)
print(bureau_summary.shape)
print(previous_summary.shape)

(307511, 26)
(305811, 10)
(338857, 7)

In [3]:
application_clean.head()

,SK_ID_CURR,CODE_GENDER,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,CNT_CHILDREN,CNT_FAM_MEMBERS,NAME_CONTRACT_TYPE,...,employment_years,days_employed_anomaly,credit_income_ratio,credit_income_band,annuity_income_ratio,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,AMT_REQ_CREDIT_BUREAU_YEAR,TARGET
0,100002,M,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,0,1.0,Cash loans,...,1.744011,False,2.007889,Q1 - Lowest,0.121978,0.083037,0.262949,0.139376,1.0,1
1,100003,F,State servant,Higher education,Married,House / apartment,Core staff,0,2.0,Cash loans,...,3.252567,False,4.790750,Q3,0.132217,0.311267,0.622246,NaN,0.0,0
2,100004,M,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,0,1.0,Revolving loans,...,0.616016,False,2.000000,Q1 - Lowest,0.100000,NaN,0.555912,0.729567,0.0,0
3,100006,F,Working,Secondary / secondary special,Civil marriage,House / apartment,Laborers,0,2.0,Cash loans,...,8.320329,False,2.316167,Q2,0.219900,NaN,0.650442,NaN,NaN,0
4,100007,M,Working,Secondary / secondary special,Single / not married,House / apartment,Core staff,0,1.0,Cash loans,...,8.317591,False,4.222222,Q3,0.179963,NaN,0.322738,NaN,0.0,0

In [4]:
bureau_summary.head()

,SK_ID_CURR,previous_credit_count,active_credit_count,closed_credit_count,overdue_credit_count,total_credit_sum,avg_credit_amount,max_overdue_amount,total_debt,overdue_credit_rate
0,100001,7,3,4,0,1453365.000,207623.571429,0.0,596686.5,0.0
1,100002,8,2,6,0,865055.565,108131.945625,0.0,245781.0,0.0
2,100003,4,1,3,0,1017400.500,254350.125000,0.0,0.0,0.0
3,100004,2,0,2,0,189037.800,94518.900000,0.0,0.0,0.0
4,100005,3,2,1,0,657126.000,219042.000000,0.0,568408.5,0.0

In [5]:
previous_summary.head()

,SK_ID_CURR,previous_application_count,approved_application_count,refused_application_count,avg_previous_credit,avg_previous_annuity,previous_refusal_rate
0,100001,1,1,0,23787.00,3951.000,0.0
1,100002,1,1,0,179055.00,9251.775,0.0
2,100003,3,3,0,484191.00,56553.990,0.0
3,100004,1,1,0,20106.00,5357.250,0.0
4,100005,2,1,0,20076.75,4813.200,0.0

In [6]:
print(
    application_clean["SK_ID_CURR"].duplicated().sum()
)

0

In [7]:
print(
    bureau_summary["SK_ID_CURR"].duplicated().sum()
)

0

In [8]:
print(
    previous_summary["SK_ID_CURR"].duplicated().sum()
)

0

In [9]:
application_clean[
    [
        "SK_ID_CURR",
        "age",
        "age_band",
        "employment_years",
        "days_employed_anomaly",
        "credit_income_ratio",
        "credit_income_band",
        "annuity_income_ratio",
        "TARGET"
    ]
].head(20)

,SK_ID_CURR,age,age_band,employment_years,days_employed_anomaly,credit_income_ratio,credit_income_band,annuity_income_ratio,TARGET
0,100002,25.902806,25-34,1.744011,False,2.007889,Q1 - Lowest,0.121978,1
1,100003,45.900068,45-54,3.252567,False,4.790750,Q3,0.132217,0
2,100004,52.145106,45-54,0.616016,False,2.000000,Q1 - Lowest,0.100000,0
3,100006,52.032854,45-54,8.320329,False,2.316167,Q2,0.219900,0
4,100007,54.570842,45-54,8.317591,False,4.222222,Q3,0.179963,0
5,100008,46.381930,45-54,4.347707,False,4.954500,Q3,0.277955,0
6,100009,37.722108,35-44,8.569473,False,9.127053,Q4 - Highest,0.241526,0
7,100010,51.608487,45-54,1.229295,False,4.250000,Q3,0.116875,0
8,100011,55.028063,55+,NaN,True,9.063200,Q4 - Highest,0.300680,0
9,100012,39.613963,35-44,5.527721,False,3.000000,Q2,0.150000,0
10,100014,27.917864,25-34,1.859001,False,5.800000,Q4 - Highest,0.188240,0
11,100015,55.898700,55+,NaN,True,3.861746,Q3,0.277947,0
12,100016,36.793977,35-44,7.438741,False,1.198000,Q1 - Lowest,0.087133,0
13,100017,38.565366,35-44,8.290212,False,4.082080,Q3,0.128740,0
14,100018,39.926078,35-44,0.555784,False,4.093548,Q3,0.173429,0
15,100019,23.895962,<25,3.167693,False,1.903314,Q1 - Lowest,0.128000,0
16,100020,35.403149,35-44,3.605749,False,4.718542,Q3,0.242125,0
17,100021,26.765229,25-34,0.522930,False,3.333333,Q3,0.166667,0
18,100022,48.509240,45-54,21.366188,False,1.400000,Q1 - Lowest,0.070000,0
19,100023,31.069131,25-34,5.579740,False,6.049900,Q4 - Highest,0.195150,0

In [10]:
application_clean[
    [
        "age",
        "employment_years",
        "credit_income_ratio",
        "annuity_income_ratio"
    ]
].describe()

,age,employment_years,credit_income_ratio,annuity_income_ratio
count,307511.000000,252137.000000,307511.000000,307499.000000
mean,43.906900,6.527500,3.957570,0.180930
std,11.947950,6.402081,2.689728,0.094574
min,20.503765,-0.000000,0.004808,0.000224
25%,33.984942,2.099932,2.018667,0.114782
50%,43.121150,4.511978,3.265067,0.162833
75%,53.886379,8.692676,5.159880,0.229067
max,69.073238,49.040383,84.736842,1.875965

In [11]:
application_clean[
    "days_employed_anomaly"
].value_counts()

days_employed_anomaly
False    252137
True      55374
Name: count, dtype: int64